### ISSUE TITLE
Do we need to use autoprefixer in watch.compass task?

### ISSUE THREAD

**Issue by eightdotthree** [BarkleyREI/brei-grunt-config#3]
Autoprefixer is running in the watch.js. It runs on build so I am not sure it needs to run here as well.

**Comment by JDillon522** [comment]
True story: I don't even know what autoprefixer does.

**Comment by nessthehero** [comment]
Autoprefixer adds the vendor prefixes for edge CSS attributes.

If we're only ever going to run the server in Chrome, then sure, we can take it out of watch. I don't really see the harm in keeping it, though.
